---
title: "STAT 430 Data Manipulation"
output: pdf_document
date: "2026-07-16"
---

# This file evaluates the sequences generated by python and provide data for R.
# Functions for separate tests:
```{r}
# x is a sequence of random numbers between 1 and 1024 inclusively
# this is normalized entropy
entropy <- function(x, m=1024) {
  counts <- tabulate(x, nbins=1024) # 1024 possible integers
  p <- counts / length(x) # probability of occurance of each integer
  p <- p[p>0] # remove 0 probabilities
  H <- -sum(p * log(p, base=2)) # Shannon Entropy
  return(H / log(m, base=2)) # normalize to [0,1]
}

runsTest <- function(x) {
  z <- randtests::runs.test(x)$statistic
  return(as.vector(exp(-z^2/2))) # apply gaussian function to score the discrepancy (smaller dis, higher score)
}

TestPi <- function(x, m=1024) {
  x <- x / m
  n <- length(x) / 2
  u.1 <- x[1:n]
  u.2 <- x[-(1:n)]
  nor <- sqrt(u.1^2+u.2^2) # norm of each pair
  pi.est <- 4 * mean(nor < 1)
  z <- pi.est - pi # discrepancy from real pi
  return(exp(-z^2/2)) # apply gaussian function to score the discrepancy (smaller dis, higher score)
}

TestACF <- function(x) {
  x.acf <- acf(x, lag.max=50, plot=FALSE)
  ACF <- abs(x.acf$acf[-1]) # remove first lag, and take abs value
  n.lags <- length(ACF) # total lags used, here is 50
  avg.ACF <- mean(ACF)
  return(max(0, 1 - avg.ACF))
}

TestUniformity <- function(x, m=1024) {
  counts <- tabulate(x, nbins=m) # 1024 possible integers
  p <- counts / length(x) # probability of occurrence of each integer
  D <- sum(abs(p - (1/m))) / 2 # total variation distance
  return(max(0, 1-D))
}

# FFT spectral score for perodicity
SpectralScore <- function(x) {
  x <- x - mean(x)

  power <- Mod(fft(x))^2
  power <- power[2:(floor(length(x) / 2) + 1)]

  p <- power / sum(power)
  p <- p[p > 1e-15]

  return(-sum(p * log(p)) / log(length(power)))
}
#SpectralScore(c(1,2,3,1,2,3,1,2))

# checks for repeated patterns. adjusts penalty based on repetition length
RepetitionScore.period <- function(x, min_overlap = 100, tau = length(x) / 2) {
  n <- length(x)
  chance <- sum((table(x) / n)^2)

  penalties <- sapply(1:(n - min_overlap), function(k) {
    match_rate <- mean(x[1:(n - k)] == x[(k + 1):n])

    strength <- max(0, (match_rate - chance) / (1 - chance))
    period_weight <- exp(-(k / tau)^2)

    strength * period_weight
  })

  return(1 - max(penalties))
}

# checks for repeated patterns regardless repetition length
RepetitionScore <- function(x, min_overlap = 100) {
  n <- length(x)

  chance <- sum((table(x) / n)^2)

  match_rates <- sapply(1:(n - min_overlap), function(k) {
    mean(x[1:(n - k)] == x[(k + 1):n]) # match rate
  })

  # output 0 if no matches
  strength <- max(0, max((match_rates - chance) / (1 - chance)))
  
  return(max(0, 1 - strength))
}

RepetitionScore(rep(c(1,2,3),500))

```

# Evaluate Function:
```{r}
# evaluates the randomness score of a sequence
EvaluateSeq <- function(x, m=1024) {
  entropy.score <- entropy(x, m=m)
  acf.score <- TestACF(x)
  uni.score <- TestUniformity(x, m=m)
  runs.score <- runsTest(x)
  pi.score <- TestPi(x, m=m)
  rep.score <- RepetitionScore(x)
  
  entropy.weight <- 1/6
  acf.weight <- 1/6
  uni.weight <- 1/6
  runs.weight <- 1/6
  pi.weight <- 1/6
  rep.weight <- 1 - entropy.weight - acf.weight - uni.weight - runs.weight - pi.weight

  return(entropy.weight * entropy.score +
         acf.weight * acf.score +
         uni.weight * uni.score +
         runs.weight * runs.score +
         pi.weight * pi.score +
         rep.weight * rep.score)
}
```

# Function for evaluating each row (sequence) of a data frame
```{r}
encode.seq.df <- function(seq.df, algo) {
  # total length 1500, separate into 5 levels
  lengths <- c(300, 600, 900, 1200, 1500)
  final.df <- list(score=c(), seed=c(), len=c()) # data frame for output
  seq.matrix <- as.matrix(seq.df)
  n.seeds <- length(seq.df$"X..Seed")
  
  for(length in lengths) {
    final.df$score <- c(final.df$score,
                        apply(seq.matrix[,1:length], 1, EvaluateSeq))
    final.df$seed <- c(final.df$seed,
                       seq.df$"X..Seed")
    final.df$len <- c(final.df$len,
                      rep(length, times=n.seeds))
  }
  
  final.df$algo <- rep(algo, times=length(final.df$score))
  
  return(as.data.frame(final.df))
}
```

# Read sequences
```{r}
seq.LCG <- read.csv('seq_data/430_LCG_1500.csv', header=TRUE)
head(seq.LCG)
seq.XOR <- read.csv('seq_data/430_Mersenne_1500.csv', header=TRUE)
head(seq.XOR)
seq.DEC <- read.csv('seq_data/430_Decimal_1500.csv', header=TRUE)
head(seq.DEC)
```

# Evaluate each df, and combine, and write to file
```{r}
data.LCG <- encode.seq.df(seq.LCG, 'LCG')
head(data.LCG)
data.XOR <- encode.seq.df(seq.XOR, 'XOR')
head(data.XOR)
data.DEC <- encode.seq.df(seq.DEC, 'DEC')
head(data.DEC)
data.rng <- rbind(data.LCG, data.XOR, data.DEC)
write.csv(data.rng, 'RNG_Data_withseed_R.csv')
```

# separate levels for seeds
```{r}
# indicates the level of a seed
seedEva <- function(seed) {
  if (seed <= 250) {
    return('low')
  } else if (seed <= 500) {
    return('low|mid') # middle low
  } else if (seed <= 750) {
    return('high|mid') # middle high
  } else if (seed <= 1000) {
    return('high')
  } else {
    return(NA)
  }
}

data.rng$seed <- sapply(data.rng$seed, seedEva)
#write.csv(data.rng, 'RNG_Data_R.csv')
```

# write off NA
```{r}
#data.rng$score[is.na(data.rng$score)] <- 0
#write.csv(data.rng, 'RNG_Data_R.csv')
```

# draft
```{r, eval=FALSE}

print('LCG')
mat.LCG <- as.matrix(seq.LCG)

RepetitionScore(mat.LCG[1,1:700])
RepetitionScore(mat.LCG[1,1:1000])
RepetitionScore(mat.LCG[1,1:1200])
RepetitionScore(mat.LCG[1,1:1300])
RepetitionScore(mat.LCG[1,1:1400])
RepetitionScore(mat.LCG[1,])
RepetitionScore.period(mat.LCG[1,1:1000])
RepetitionScore.period(mat.LCG[1,1:1200])
RepetitionScore.period(mat.LCG[1,1:1300])
RepetitionScore.period(mat.LCG[1,1:1400])
RepetitionScore(mat.LCG[1,])

print('XOR')
mat.XOR <- as.matrix(seq.XOR)
RepetitionScore(mat.XOR[1,1:400])
RepetitionScore(mat.XOR[1,1:700])
RepetitionScore(mat.XOR[1,1:800])
RepetitionScore(mat.XOR[1,1:900])
RepetitionScore(mat.XOR[1,1:1000])
RepetitionScore(mat.XOR[1,1:1200])
RepetitionScore(mat.XOR[1,1:1300])
RepetitionScore(mat.XOR[1,1:1400])
RepetitionScore(mat.XOR[1,])

print('DEC')
mat.DEC <- as.matrix(seq.DEC)
RepetitionScore(mat.DEC[1,1:400])
RepetitionScore(mat.DEC[1,])
```

# test NA
```{r, eval=FALSE}
entropy(mat.XOR[221,])
TestACF(mat.XOR[221,])
entropy(c(1, 3, 5, 7, 9, 11, 13, 15, 17, 19), m=20)
entropy(c(1, 12, 6, 2, 19, 6, 15, 18, 4, 8), m=20)
entropy(c(1, 2, 2, 3, 3, 3, 4, 4, 4, 4), m=20)
TestUniformity(c(2, 14, 19, 3, 17, 28, 30, 5, 23, 15), m=31)
entropy(c(1, 11, 10, 7, 29, 2, 14, 19, 3, 17), m=31)
entropy(c(2, 14, 19, 3, 17, 28, 30, 5, 23, 15, 22, 12, 13, 16, 25), m=31)
```